name: farmer_crate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  google_fonts: ^6.2.1
  table_calendar: ^3.0.9
  http: ^1.2.2
  shared_preferences: ^2.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  crypto: ^3.0.3
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.2.5
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/farmer.jpg
    - assets/getstartbackimg.png
    - assets/verify.jpg
    - assets/3127.jpg
    - assets/3175990.jpg
    - assets/11264.jpg
    - assets/farmerhome.jpg
    - assets/resetpage.jpg
    - assets/getstart.png
    - assets/get.png
