// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnXI7G6wPoltsIdaJVqToF5Ag7x2FK0o',
    appId: '1:378078726342:web:bacfd612439a96efb7efc7',
    messagingSenderId: '378078726342',
    projectId: 'farmercrate-c62de',
    authDomain: 'farmercrate-c62de.firebaseapp.com',
    storageBucket: 'farmercrate-c62de.firebasestorage.app',
    measurementId: 'G-E5G11CMX1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3HRV2xBuNXBdrGGPbYYtf2IlRvPezzsY',
    appId: '1:378078726342:android:a5098b05a46ade6cb7efc7',
    messagingSenderId: '378078726342',
    projectId: 'farmercrate-c62de',
    storageBucket: 'farmercrate-c62de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5oyNhx04smfUil__OUamhTSYtsmseC_8',
    appId: '1:378078726342:ios:42faf11dd501bec6b7efc7',
    messagingSenderId: '378078726342',
    projectId: 'farmercrate-c62de',
    storageBucket: 'farmercrate-c62de.firebasestorage.app',
    androidClientId: '378078726342-4o955sqp0p85j1egddvm35oeksifs6es.apps.googleusercontent.com',
    iosClientId: '378078726342-7qscei11afthiupeirvuulq23kjb7f26.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerCrate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5oyNhx04smfUil__OUamhTSYtsmseC_8',
    appId: '1:378078726342:ios:42faf11dd501bec6b7efc7',
    messagingSenderId: '378078726342',
    projectId: 'farmercrate-c62de',
    storageBucket: 'farmercrate-c62de.firebasestorage.app',
    androidClientId: '378078726342-4o955sqp0p85j1egddvm35oeksifs6es.apps.googleusercontent.com',
    iosClientId: '378078726342-7qscei11afthiupeirvuulq23kjb7f26.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmerCrate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPnXI7G6wPoltsIdaJVqToF5Ag7x2FK0o',
    appId: '1:378078726342:web:a27c7b20185e79c7b7efc7',
    messagingSenderId: '378078726342',
    projectId: 'farmercrate-c62de',
    authDomain: 'farmercrate-c62de.firebaseapp.com',
    storageBucket: 'farmercrate-c62de.firebasestorage.app',
    measurementId: 'G-M6TMTYKPV9',
  );
}
